import re

with open("profiler/app.py", "r", encoding="utf-8") as f:
    code = f.read()

# Expand translations dictionary to cover missing terms
TRANSLATIONS_REPLACEMENT = r'''TRANSLATIONS = {
    "English": {
        "SISTEMA ACTIVO": "ACTIVE SYSTEM",
        "Cargando estado...": "Loading status...",
        "Tiempo restante: -- s": "Time remaining: -- s",
        "🔄 Forzar Rotación Ahora": "🔄 Force Rotation Now",
        "▶️ Iniciar Todos los Monitores": "▶️ Start All Monitors",
        "⏸️ Pausar Todos los Monitores": "⏸️ Pause All Monitors",
        "Configuración Global de Tiempos y UI": "Global Timing and UI Settings",
        "Carpeta Global de Cookies (.txt):": "Global Cookies Folder (.txt):",
        "Cambiar carpeta": "Change folder",
        "Monitor para Popups (Global):": "Popup Monitor (Global):",
        "Actualizar monitores": "Update monitors",
        "Idioma (Global):": "Language (Global):",
        "Tiempo base de rotación (Segundos):": "Base rotation time (Seconds):",
        "Tiempo aleatorio extra (Segundos):": "Extra random time (Seconds):",
        "Iniciar app con Windows (global)": "Start app with Windows (global)",
        "💾 Guardar Configuración Global": "💾 Save Global Config",
        "Otras Utilidades y Acciones de Sistema": "Other Utilities and System Actions",
        "🔄 Reiniciar Aplicación (Actualizar a nuevo código)": "🔄 Restart App (Update to new code)",
        "Abrir otra ventana (Nueva Instancia)": "Open another window (New Instance)",
        "Archivos en carpeta: 0": "Files in folder: 0",
        "➕ Importar archivo de Cookie (.txt)": "➕ Import Cookie file (.txt)",
        "📁 Abrir carpeta de cookies": "📁 Open cookies folder",
        " ⚙️ Opciones Globales ": " ⚙️ Global Options ",
        " Logs (Registro) ": " Logs (Registry) ",
        " Monitoreo y Perfiles ": " Monitoring & Profiles ",
        "Historial de popups": "Popup History",
        "Ver Historial de Popups": "View Popup History",
        "UID:": "UID:",
        "Usuario X (sin @):": "X User (without @):",
        "Cuenta X (@usuario o URL):": "X Account (@user or URL):",
        "Detectar posts": "Detect posts",
        "Detectar Posts/Tweets": "Detect Posts/Tweets",
        "Detectar replies": "Detect replies",
        "Detectar Respuestas (Replies)": "Detect Replies",
        "Detectar retweets": "Detect retweets",
        "Detectar Retweets": "Detect Retweets",
        "Mostrar popup de alerta": "Show alert popup",
        "Modo descarga:": "Download Mode:",
        "Modo de Descarga:": "Download Mode:",
        "Ruta salida:": "Output Path:",
        "Directorio de Descarga:": "Download Directory:",
        "Cambiar Directorio": "Change Directory",
        "Elegir carpeta": "Choose folder",
        "Chequeo min (seg):": "Check min (sec):",
        "Chequeos aleatorios:": "Random checks:",
        "Min (seg):": "Min (sec):",
        "Chequeo max (seg):": "Check max (sec):",
        "Max (seg):": "Max (sec):",
        "Auto-cerrar popup": "Auto-close popup",
        "Segundos popup:": "Popup seconds:",
        "Autoplay de Video en Popup": "Autoplay Video in Popup",
        "Auto-reproducir gif/video": "Auto-play gif/video",
        "Iniciar monitoreo automáticamente": "Start monitoring automatically",
        "Ignorar historial (Baseline nueva)": "Ignore history (New Baseline)",
        "Programación:": "Schedule:",
        "Modo de ejecución:": "Execution mode:",
        "Horas exactas (HH:MM, separadas por coma):": "Exact times (HH:MM, comma separated):",
        "Horas (08:00, 14:30):": "Hours (08:00, 14:30):",
        "Retraso inicial (min):": "Initial delay (min):",
        "Retrasar inicio (min):": "Delay start (min):",
        "Detener tras (min, 0=inf):": "Stop after (min, 0=inf):",
        "💾 Guardar Perfil": "💾 Save Profile",
        "Guardar perfil": "Save profile",
        "✨ Nuevo Perfil (Limpiar)": "✨ New Profile (Clear)",
        "Nuevo UID": "New UID",
        "🗑️ Eliminar Perfil": "🗑️ Delete Profile",
        "Eliminar perfil": "Delete profile",
        "▶ Iniciar Seleccionado": "▶ Start Selected",
        "▶ Iniciar monitor": "▶ Start monitor",
        "⏸ Detener Seleccionado": "⏸ Stop Selected",
        "⏹ Detener monitor": "⏹ Stop monitor",
        "Configuración global guardada.": "Global configuration saved.",
        "Perfil guardado": "Profile saved",
        "Perfil eliminado": "Profile deleted",
        "Detén el monitor antes de eliminar el perfil": "Stop the monitor before deleting the profile",
        "Ese perfil ya está corriendo": "That profile is already running",
        "Automatico": "Automatic",
        "Automático": "Automatic",
        "Perfiles de Monitor": "Monitor Profiles",
        "Perfiles Guardados": "Saved Profiles",
        "Configuracion de deteccion del Perfil": "Profile detection settings",
        "Filtrar por perfil:": "Filter by profile:",
        "Refrescar lista": "Refresh list",
        "Limpiar Log": "Clear Log",
        "Solo notificaciones": "Notifications only",
        "Descargar cuenta completa (advertencia)": "Download full account (warning)",
        "Descargar actividad seleccionada (en monitoreo)": "Download selected activity (while monitoring)",
        "Descargar solo media subida por la cuenta": "Download only media uploaded by account",
        "Intervalos": "Intervals",
        "Horas exactas": "Exact hours",
        "Advertencia descarga": "Download warning",
        "Fecha/Hora": "Date/Time",
        "Tipo": "Type",
        "Media": "Media",
        "ID": "ID",
        "Refrescar": "Refresh",
        "Limpiar UID": "Clear UID",
        "Cerrar": "Close",
        "Cerrar Alerta": "Close Alert",
        "Copiar URL": "Copy URL",
        "Abrir post en navegador": "Open post in browser",
        "Abrir post": "Open post",
        "Abrir externamente": "Open externally",
        "Abrir Quote": "Open Quote",
        "Bucle": "Loop",
        "Perfil:": "Profile:"
    }
}
'''
code = re.sub(r'TRANSLATIONS = \{\n\s+"English": \{.*?\n\}\n\}', TRANSLATIONS_REPLACEMENT, code, flags=re.DOTALL)

with open("profiler/app.py", "w", encoding="utf-8") as f:
    f.write(code)
